### ISSUE TITLE
DYNAMICPTR_TOP must be a number

### ISSUE THREAD

**Issue by mikebolt** [dcodeIO/webassembly#12]
After following your instructions in the README I get the following issue in Chrome 59:

`
src:211 Uncaught (in promise) LinkError: Import #0 module="env" function="DYNAMICTOP_PTR" error: global import must be a number
    at then.then.buffer (http://127.0.0.1:8080/node_modules/webassembly/dist/webassembly.js:212:37)
    at <anonymous>
`

However it works correctly in Firefox Nightly.

**Comment by mikebolt** [comment]
This error is now mysteriously gone.

**Comment by dcodeIO** [comment]
There shouldn't be a `env.DYNAMICTOP_PTR` import by default unless your program adds it. At least I haven't seen it yet.

**Comment by mikebolt** [comment]
I think Chrome was caching an old version of my .wasm file generated by emcc. No issues now. Thanks for the library!

**Comment by gabrielfreire** [comment]
Hi guys, i landed in this issue because i'm having a similar problem trying to load [Pyodide](https://github.com/iodide-project/pyodide) in `NodeJS` using `webassembly` npm package

So, that's how my code looks like
```javascript
const path = require('path');
const fs = require('fs');
const wa = require('webassembly');
const wasmPath = path.join(__dirname, '/src/wasm/pyodide.asm.wasm');
const memory = new WebAssembly.Memory({initial:8192, maximum:8192});
const table = new WebAssembly.Table({ initial: 16384, element: "anyfunc" });
const importObj = { 
    memory: memory, 
    table: table, 
    tableBase: 0, 
    memoryBase: 0
};
wa.load(wasmPath, {imports: importObj}).then((module) => {
    console.log(module.exports);
}).catch((err) => {
    console.log(`some error: ${err}`);
});
```

and that's the error i'm getting
```
LinkError: Import #4 module="env" function="DYNAMICTOP_PTR" error: global import must be a number
```
would you have any idea of what's that?


**Edit:** i found out that the problem is that i also need to load a metadata file `pyodide.asm.data.js` and `pyodide.asm.data` to download the python standard library and dynamically load it, unfortunately those files were generated depending heavily on the Browser API, i was able to make it almost work by overriding some exposed methods but other ones are not exposed and i couldn't override

**Edit2:** i made it work!
